# Generated by Django 5.1.4 on 2025-01-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_client_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total',
            new_name='total_amount',
        ),
    ]
