# Generated by Django 5.1.4 on 2025-01-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_rename_total_invoice_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
