# Generated by Django 5.1.4 on 2025-01-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='business_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='business_website',
            field=models.URLField(null=True),
        ),
    ]
