# Generated by Django 5.1.4 on 2025-01-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_client_onwer_invoice_onwer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='onwer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='onwer',
        ),
    ]
